# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from lambda_python_sdk import Lambda

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        lambda = Lambda(
        
            username = 'YOUR_USERNAME',
            password = 'YOUR_PASSWORD',
        
            access_token = 'YOUR_BEARER_TOKEN'
        )
        self.assertIsNotNone(lambda)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
