# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


ErrorCode = Literal["global/unknown", "global/invalid-api-key", "global/account-inactive", "global/invalid-address", "global/invalid-parameters", "global/object-does-not-exist", "global/quota-exceeded", "instance-operations/launch/insufficient-capacity", "instance-operations/launch/file-system-in-wrong-region", "instance-operations/launch/file-systems-not-supported", "ssh-keys/key-in-use"]
