# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from lambda_python_sdk.pydantic.error import Error
from lambda_python_sdk.pydantic.error_response_body_field_errors import ErrorResponseBodyFieldErrors

class ErrorResponseBody(BaseModel):
    error: Error = Field(alias='error')

    field_errors: typing.Optional[ErrorResponseBodyFieldErrors] = Field(None, alias='field_errors')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
