# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from lambda_python_sdk.pydantic.instance_type_specs import InstanceTypeSpecs

class InstanceType(BaseModel):
    # Long name of the instance type
    description: str = Field(alias='description')

    # Name of an instance type
    name: str = Field(alias='name')

    # Price of the instance type, in US cents per hour
    price_cents_per_hour: int = Field(alias='price_cents_per_hour')

    specs: InstanceTypeSpecs = Field(alias='specs')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
