# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from lambda_python_sdk.pydantic.instance_name import InstanceName
from lambda_python_sdk.pydantic.ssh_key_name import SshKeyName

class InstanceCreateInstancesRequest(BaseModel):
    # Short name of a region
    region_name: str = Field(alias='region_name')

    # Name of an instance type
    instance_type_name: str = Field(alias='instance_type_name')

    # Names of the SSH keys to allow access to the instances. Currently, exactly one SSH key must be specified.
    ssh_key_names: typing.List[SshKeyName] = Field(alias='ssh_key_names')

    # Names of the file systems to attach to the instances. Currently, only one (if any) file system may be specified.
    file_system_names: typing.Optional[typing.List[str]] = Field(None, alias='file_system_names')

    # Number of instances to launch
    quantity: typing.Optional[int] = Field(None, alias='quantity')

    name: typing.Optional[InstanceName] = Field(None, alias='name')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
