# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class InstanceTypeSpecs(BaseModel):
    # Number of virtual CPUs
    vcpus: int = Field(alias='vcpus')

    # Amount of RAM, in gibibytes (GiB)
    memory_gib: int = Field(alias='memory_gib')

    # Amount of storage, in gibibytes (GiB).
    storage_gib: int = Field(alias='storage_gib')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
