# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from lambda_python_sdk.pydantic.instance import Instance

class InstanceTerminateInstanceResponseData(BaseModel):
    # List of instances that were terminated. Note: this list might not contain all instances requested to be terminated.
    terminated_instances: typing.List[Instance] = Field(alias='terminated_instances')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
