# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from lambda_python_sdk.paths.file_systems.get import GetList
from lambda_python_sdk.apis.tags.file_system_api_raw import FileSystemApiRaw


class FileSystemApi(
    GetList,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: FileSystemApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = FileSystemApiRaw(api_client)
