# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from lambda_python_sdk.paths.instance_types.get import GetList
from lambda_python_sdk.apis.tags.instance_type_api_raw import InstanceTypeApiRaw


class InstanceTypeApi(
    GetList,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: InstanceTypeApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = InstanceTypeApiRaw(api_client)
