# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from lambda_python_sdk.paths.instance_operations_launch.post import CreateInstances
from lambda_python_sdk.paths.instances_id.get import GetDetails
from lambda_python_sdk.paths.instances.get import ListRunningInstances
from lambda_python_sdk.paths.instance_operations_restart.post import RestartInstances
from lambda_python_sdk.paths.instance_operations_terminate.post import TerminateInstance
from lambda_python_sdk.apis.tags.instance_api_raw import InstanceApiRaw


class InstanceApi(
    CreateInstances,
    GetDetails,
    ListRunningInstances,
    RestartInstances,
    TerminateInstance,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: InstanceApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = InstanceApiRaw(api_client)
