# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from lambda_python_sdk.paths.ssh_keys.post import AddSshKey
from lambda_python_sdk.paths.ssh_keys.get import GetList
from lambda_python_sdk.apis.tags.key_api_raw import KeyApiRaw


class KeyApi(
    AddSshKey,
    GetList,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: KeyApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = KeyApiRaw(api_client)
