# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from lambda_python_sdk.paths.ssh_keys_id.delete import Remove
from lambda_python_sdk.apis.tags.ssh_key_api_raw import SSHKeyApiRaw


class SSHKeyApi(
    Remove,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SSHKeyApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SSHKeyApiRaw(api_client)
