# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

import unittest

import lambda_python_sdk
from lambda_python_sdk.model.instance_restart_instances_request import InstanceRestartInstancesRequest
from lambda_python_sdk import configuration


class TestInstanceRestartInstancesRequest(unittest.TestCase):
    """InstanceRestartInstancesRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
