# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

import unittest

import lambda_python_sdk
from lambda_python_sdk.model.instance_type import InstanceType
from lambda_python_sdk import configuration


class TestInstanceType(unittest.TestCase):
    """InstanceType unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
