# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from lambda_python_sdk.type.error_code import ErrorCode

class RequiredError(TypedDict):
    code: ErrorCode

    # Detailed description of the error
    message: str

class OptionalError(TypedDict, total=False):
    # Suggestion of possible ways to fix the error.
    suggestion: typing.Optional[str]

class Error(RequiredError, OptionalError):
    pass
