# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from lambda_python_sdk.type.region import Region
from lambda_python_sdk.type.user import User

class RequiredFileSystem(TypedDict):
    # Unique identifier (ID) of a file system
    id: str

    # Name of a file system
    name: str

    # A date and time, formatted as an ISO 8601 time stamp
    created: str

    created_by: User

    # Absolute path indicating where on instances the file system will be mounted
    mount_point: str

    region: Region

    # Whether the file system is currently in use by an instance. File systems that are in use cannot be deleted.
    is_in_use: bool

class OptionalFileSystem(TypedDict, total=False):
    # Approximate amount of storage used by the file system, in bytes. This value is an estimate that is updated every several hours.
    bytes_used: int

class FileSystem(RequiredFileSystem, OptionalFileSystem):
    pass
