# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredInstanceTypeSpecs(TypedDict):
    # Number of virtual CPUs
    vcpus: int

    # Amount of RAM, in gibibytes (GiB)
    memory_gib: int

    # Amount of storage, in gibibytes (GiB).
    storage_gib: int

class OptionalInstanceTypeSpecs(TypedDict, total=False):
    pass

class InstanceTypeSpecs(RequiredInstanceTypeSpecs, OptionalInstanceTypeSpecs):
    pass
