# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from lambda_python_sdk.type.instance_name import InstanceName
from lambda_python_sdk.type.instance_type import InstanceType
from lambda_python_sdk.type.region import Region
from lambda_python_sdk.type.ssh_key_name import SshKeyName

class RequiredInstance(TypedDict):
    # Unique identifier (ID) of an instance
    id: str

    # The current status of the instance
    status: str

    # Names of the SSH keys allowed to access the instance
    ssh_key_names: typing.List[SshKeyName]

    # Names of the file systems, if any, attached to the instance
    file_system_names: typing.List[str]

class OptionalInstance(TypedDict, total=False):
    name: InstanceName

    # IPv4 address of the instance
    ip: typing.Optional[str]

    region: Region

    instance_type: InstanceType

    # Hostname assigned to this instance, which resolves to the instance's IP.
    hostname: typing.Optional[str]

    # Secret token used to log into the jupyter lab server hosted on the instance.
    jupyter_token: typing.Optional[str]

    # URL that opens a jupyter lab notebook on the instance.
    jupyter_url: typing.Optional[str]

class Instance(RequiredInstance, OptionalInstance):
    pass
