# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from lambda_python_sdk.type.instance_name import InstanceName
from lambda_python_sdk.type.ssh_key_name import SshKeyName

class RequiredInstanceCreateInstancesRequest(TypedDict):
    # Short name of a region
    region_name: str

    # Name of an instance type
    instance_type_name: str

    # Names of the SSH keys to allow access to the instances. Currently, exactly one SSH key must be specified.
    ssh_key_names: typing.List[SshKeyName]

class OptionalInstanceCreateInstancesRequest(TypedDict, total=False):
    # Names of the file systems to attach to the instances. Currently, only one (if any) file system may be specified.
    file_system_names: typing.List[str]

    # Number of instances to launch
    quantity: int

    name: InstanceName

class InstanceCreateInstancesRequest(RequiredInstanceCreateInstancesRequest, OptionalInstanceCreateInstancesRequest):
    pass
