# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredInstanceCreateInstancesResponseData(TypedDict):
    # The unique identifiers (IDs) of the launched instances. Note: if a quantity was specified, fewer than the requested quantity might have been launched.
    instance_ids: typing.List[str]

class OptionalInstanceCreateInstancesResponseData(TypedDict, total=False):
    pass

class InstanceCreateInstancesResponseData(RequiredInstanceCreateInstancesResponseData, OptionalInstanceCreateInstancesResponseData):
    pass
