# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from lambda_python_sdk.type.ssh_key_name import SshKeyName
from lambda_python_sdk.type.ssh_private_key import SshPrivateKey
from lambda_python_sdk.type.ssh_public_key import SshPublicKey

class RequiredSshKey(TypedDict):
    # Unique identifier (ID) of an SSH key
    id: str

    name: SshKeyName

    public_key: SshPublicKey

class OptionalSshKey(TypedDict, total=False):
    private_key: SshPrivateKey

class SshKey(RequiredSshKey, OptionalSshKey):
    pass
