# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredUser(TypedDict):
    # Unique identifier for the user
    id: str

    # Email address of the user
    email: str

    # Status of the user's account
    status: str

class OptionalUser(TypedDict, total=False):
    pass

class User(RequiredUser, OptionalUser):
    pass
