# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lambda_python_sdk import schemas  # noqa: F401


class ErrorCode(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Unique identifier for the type of error
    """


    class MetaOapg:
        enum_value_to_name = {
            "global/unknown": "GLOBAL_UNKNOWN",
            "global/invalid-api-key": "GLOBAL_INVALIDAPIKEY",
            "global/account-inactive": "GLOBAL_ACCOUNTINACTIVE",
            "global/invalid-address": "GLOBAL_INVALIDADDRESS",
            "global/invalid-parameters": "GLOBAL_INVALIDPARAMETERS",
            "global/object-does-not-exist": "GLOBAL_OBJECTDOESNOTEXIST",
            "global/quota-exceeded": "GLOBAL_QUOTAEXCEEDED",
            "instance-operations/launch/insufficient-capacity": "INSTANCEOPERATIONS_LAUNCH_INSUFFICIENTCAPACITY",
            "instance-operations/launch/file-system-in-wrong-region": "INSTANCEOPERATIONS_LAUNCH_FILESYSTEMINWRONGREGION",
            "instance-operations/launch/file-systems-not-supported": "INSTANCEOPERATIONS_LAUNCH_FILESYSTEMSNOTSUPPORTED",
            "ssh-keys/key-in-use": "SSHKEYS_KEYINUSE",
        }
    
    @schemas.classproperty
    def GLOBAL_UNKNOWN(cls):
        return cls("global/unknown")
    
    @schemas.classproperty
    def GLOBAL_INVALIDAPIKEY(cls):
        return cls("global/invalid-api-key")
    
    @schemas.classproperty
    def GLOBAL_ACCOUNTINACTIVE(cls):
        return cls("global/account-inactive")
    
    @schemas.classproperty
    def GLOBAL_INVALIDADDRESS(cls):
        return cls("global/invalid-address")
    
    @schemas.classproperty
    def GLOBAL_INVALIDPARAMETERS(cls):
        return cls("global/invalid-parameters")
    
    @schemas.classproperty
    def GLOBAL_OBJECTDOESNOTEXIST(cls):
        return cls("global/object-does-not-exist")
    
    @schemas.classproperty
    def GLOBAL_QUOTAEXCEEDED(cls):
        return cls("global/quota-exceeded")
    
    @schemas.classproperty
    def INSTANCEOPERATIONS_LAUNCH_INSUFFICIENTCAPACITY(cls):
        return cls("instance-operations/launch/insufficient-capacity")
    
    @schemas.classproperty
    def INSTANCEOPERATIONS_LAUNCH_FILESYSTEMINWRONGREGION(cls):
        return cls("instance-operations/launch/file-system-in-wrong-region")
    
    @schemas.classproperty
    def INSTANCEOPERATIONS_LAUNCH_FILESYSTEMSNOTSUPPORTED(cls):
        return cls("instance-operations/launch/file-systems-not-supported")
    
    @schemas.classproperty
    def SSHKEYS_KEYINUSE(cls):
        return cls("ssh-keys/key-in-use")
