# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lambda_python_sdk import schemas  # noqa: F401


class FileSystem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Information about a shared file system
    """


    class MetaOapg:
        required = {
            "is_in_use",
            "created",
            "mount_point",
            "name",
            "id",
            "region",
            "created_by",
        }
        
        class properties:
            id = schemas.StrSchema
            name = schemas.StrSchema
            created = schemas.StrSchema
        
            @staticmethod
            def created_by() -> typing.Type['User']:
                return User
            mount_point = schemas.StrSchema
        
            @staticmethod
            def region() -> typing.Type['Region']:
                return Region
            is_in_use = schemas.BoolSchema
            bytes_used = schemas.IntSchema
            __annotations__ = {
                "id": id,
                "name": name,
                "created": created,
                "created_by": created_by,
                "mount_point": mount_point,
                "region": region,
                "is_in_use": is_in_use,
                "bytes_used": bytes_used,
            }
    
    is_in_use: MetaOapg.properties.is_in_use
    created: MetaOapg.properties.created
    mount_point: MetaOapg.properties.mount_point
    name: MetaOapg.properties.name
    id: MetaOapg.properties.id
    region: 'Region'
    created_by: 'User'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created"]) -> MetaOapg.properties.created: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created_by"]) -> 'User': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mount_point"]) -> MetaOapg.properties.mount_point: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["region"]) -> 'Region': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_in_use"]) -> MetaOapg.properties.is_in_use: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bytes_used"]) -> MetaOapg.properties.bytes_used: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "name", "created", "created_by", "mount_point", "region", "is_in_use", "bytes_used", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created"]) -> MetaOapg.properties.created: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created_by"]) -> 'User': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mount_point"]) -> MetaOapg.properties.mount_point: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["region"]) -> 'Region': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_in_use"]) -> MetaOapg.properties.is_in_use: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bytes_used"]) -> typing.Union[MetaOapg.properties.bytes_used, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "name", "created", "created_by", "mount_point", "region", "is_in_use", "bytes_used", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        is_in_use: typing.Union[MetaOapg.properties.is_in_use, bool, ],
        created: typing.Union[MetaOapg.properties.created, str, ],
        mount_point: typing.Union[MetaOapg.properties.mount_point, str, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        id: typing.Union[MetaOapg.properties.id, str, ],
        region: 'Region',
        created_by: 'User',
        bytes_used: typing.Union[MetaOapg.properties.bytes_used, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FileSystem':
        return super().__new__(
            cls,
            *args,
            is_in_use=is_in_use,
            created=created,
            mount_point=mount_point,
            name=name,
            id=id,
            region=region,
            created_by=created_by,
            bytes_used=bytes_used,
            _configuration=_configuration,
            **kwargs,
        )

from lambda_python_sdk.model.region import Region
from lambda_python_sdk.model.user import User
