# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lambda_python_sdk import schemas  # noqa: F401


class InstanceRestartInstancesResponseData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "restarted_instances",
        }
        
        class properties:
            
            
            class restarted_instances(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Instance']:
                        return Instance
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['Instance'], typing.List['Instance']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'restarted_instances':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Instance':
                    return super().__getitem__(i)
            __annotations__ = {
                "restarted_instances": restarted_instances,
            }
    
    restarted_instances: MetaOapg.properties.restarted_instances
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["restarted_instances"]) -> MetaOapg.properties.restarted_instances: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["restarted_instances", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["restarted_instances"]) -> MetaOapg.properties.restarted_instances: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["restarted_instances", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        restarted_instances: typing.Union[MetaOapg.properties.restarted_instances, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'InstanceRestartInstancesResponseData':
        return super().__new__(
            cls,
            *args,
            restarted_instances=restarted_instances,
            _configuration=_configuration,
            **kwargs,
        )

from lambda_python_sdk.model.instance import Instance
