# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lambda_python_sdk import schemas  # noqa: F401


class KeyAddSshKeyRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The name for the SSH key. Optionally, an existing public key can be supplied for the `public_key` property. If the `public_key` property is omitted, a new key pair is generated. The private key is returned in the response.
    """


    class MetaOapg:
        required = {
            "name",
        }
        
        class properties:
        
            @staticmethod
            def name() -> typing.Type['SshKeyName']:
                return SshKeyName
        
            @staticmethod
            def public_key() -> typing.Type['SshPublicKey']:
                return SshPublicKey
            __annotations__ = {
                "name": name,
                "public_key": public_key,
            }
    
    name: 'SshKeyName'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> 'SshKeyName': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["public_key"]) -> 'SshPublicKey': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "public_key", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> 'SshKeyName': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["public_key"]) -> typing.Union['SshPublicKey', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "public_key", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        name: 'SshKeyName',
        public_key: typing.Union['SshPublicKey', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'KeyAddSshKeyRequest':
        return super().__new__(
            cls,
            *args,
            name=name,
            public_key=public_key,
            _configuration=_configuration,
            **kwargs,
        )

from lambda_python_sdk.model.ssh_key_name import SshKeyName
from lambda_python_sdk.model.ssh_public_key import SshPublicKey
